# Generated by Django 4.1.2 on 2022-10-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price_3', models.FloatField()),
                ('price_4', models.FloatField()),
                ('is_active', models.BooleanField()),
                ('is_testing', models.BooleanField()),
                ('link', models.TextField()),
            ],
        ),
    ]
