# Generated by Django 4.1.2 on 2022-10-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='q', upload_to=''),
            preserve_default=False,
        ),
    ]
