# Generated by Django 4.1.2 on 2022-10-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price_3',
        ),
    ]
