# Generated by Django 4.1.2 on 2022-11-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_item_price_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_for_name_tag',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
