# Generated by Django 4.1.2 on 2022-11-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_price_for_name_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_4',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
